# We need this because Chrome fails to start in Travis' container infrastructure due to their tight resource
# constraints.
sudo: required
language: ruby
rvm:
  - 2.6.5
install:
  - bundle install --jobs 3 --retry 3
  - nvm install 10
  - node -v
  - npm i -g yarn
  - yarn
before_script:
  - bin/rails db:setup RAILS_ENV=test
  - bin/rails assets:precompile
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start # We need xvfb - X Virtual FrameBuffer - to support applications requiring
    # graphical interfaces, such as Chrome. We do not run Chrome in headless mode, but
    # if we were, we would still need xvfb.
  - sleep 10 # Give xvfb some time to start.

script:
  - bin/rails ci
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true
services:
  - postgresql
addons:
  chrome: stable
